version: "2"

engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: "tests/phpmd.xml"

ratings:
  paths:
    - src/**.php

exclude_paths:
  - tests/**/*
  - vendor/**/*
